server:

  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100
mybatis:
  typeAliasesPackage: com.bty.blog.mybatis.entity
  mapper-locations: classpath:mappers/*xml
  config-location: classpath:mybatis-config.xml

ipfs:
  filebase:
    endpoint: https://api.filebase.io/v1/ipfs
    token: RTI5OTZDMjFDOEI0MkYzMDRBNzA6ZzA3a0RqQTBUVFJZb083NGtSd0Y1cjlJcktndVhIUFdlZFNoVEhMVTpidHktYmxvZw==



spring:
  servlet:
    multipart:
      max-file-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  banner:
    charset: UTF-8
    location: banner.text
  application:
    name: bty-blog
  profiles:
    active: dev

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql
password:
  secret: fde2.
token:
  expire-minutes: 30
  secret: dfjsfer2334re2342fdsx.
knife4j:
  enable: true
  production: false
  basic:
    enable: true
    username: btyblog
    password: btyblog123.

